### ISSUE TITLE
Error while building sdk gradle

### ISSUE THREAD

**Issue by SabarishT** [ascendia-network/sdk-java#2]
Acually I am looking for AMB Token Creation using JAVA to utilize Ambrosus Node API's. While looking for solution. I found sdk-java that is built on android. But I only need sdk. So I tried only sdk to build. While building the sdk I got following error. Can anyone please explain how to build the project or Any alternatives for JAVA. 

> Build file 'E:\AMB Blcokchain\repo\sdk-java-master\sdk\build.gradle' line: 69

* What went wrong:
A problem occurred evaluating root project 'sdk'.
> Could not get unknown property 'SONATYPE_PASSWORD' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

Is SONATYPE_USERNAME and SONATYPE_PASSWORD are required or not

**Comment by SabarishT** [comment]
And also sdk-java dependency is not working. I have tried in Eclipse Gradle and also Android Studio Gradle.
I think settings.gradle is missing. Kindly help regarding this issue. I have shared screenshot which I got.
![Screenshot3](https://user-images.githubusercontent.com/29983995/61105820-a8790b00-a498-11e9-8474-50913c1dba43.png)

**Comment by krzysztof-jelski** [comment]
Currently the gradle build file requires those 2 properties to be defined, though they can be of any value. Which means you can build the project by creating a `local.properties` with for example:
```
SONATYPE_PASSWORD=123
SONATYPE_USERNAME=321
```
The missing dependency mentioned in [this comment](https://github.com/ambrosus/sdk-java/issues/2#issuecomment-510758052) is a different problem. Currently the java sdk is not published to any maven repository. Please create another issue, as it's not connected to the building problem described here.
